title: Casey Meurer
aboutMe:
  Full Stack Developer. Project Strategist. Using Lean principles striving
  for continuous improvement.
domain: meerkat81.github.io
url: https://meerkat81.github.io

baseurl: /my_portfolio/
google_analytics: G-3LL2SX6Y08
